// FAQ 多语言数据 —— 支持 en/zh/ja/de/fr/es
// 每条 QA 保留 HTML 格式标签，仅翻译文本部分
window.FAQ_I18N = {
  langs: [
    { code: "en", name: "English" },
    { code: "zh", name: "简体中文" },
    { code: "ja", name: "日本語" },
    { code: "de", name: "Deutsch" },
    { code: "fr", name: "Français" },
    { code: "es", name: "Español" }
  ],
  qa: [
    {
      q: {
        en: "My device cannot connect to WiFi. What should I do?",
        zh: "我的设备无法连接 WiFi，该怎么办？",
        ja: "デバイスがWi-Fiに接続できません。どうすればよいですか？",
        de: "Mein Gerät kann keine WLAN-Verbindung herstellen. Was soll ich tun?",
        fr: "Mon appareil ne peut pas se connecter au Wi-Fi. Que dois-je faire ?",
        es: "Mi dispositivo no puede conectarse al WiFi. ¿Qué debo hacer?"
      },
      a: {
        en: '<p><strong>A:</strong> Please follow the steps below in order:</p><ol><li>Power on the base station and open the BFOUR+ app, and place the base station close to your phone.</li><li>Open the app and tap &quot;Add Device&quot; on the home screen.</li><li>Select your product model from the list</li><li>On the search page, tap the device that matches your model name (BF-70 or BF-80).</li><li>Tap &quot;Refresh&quot;.</li><li>Select the WiFi network you want to connect to and enter the password.</li></ol><p>Once you have completed the above steps, your device should be able to connect normally.</p><p>If you are still unable to connect, please submit your issue through the Problem Feedback feature in the app, along with a screenshot of your order, and we will process it as soon as possible.</p>',
        zh: '<p><strong>A：</strong>请按以下步骤依次操作：</p><ol><li>开启基站并打开 BFOUR+ App，将基站靠近手机放置。</li><li>在主界面点击"添加设备"。</li><li>从列表中选择您的产品型号。</li><li>在搜索页面，点击与您型号名称匹配的设备（BF-70 或 BF-80）。</li><li>点击"刷新"。</li><li>选择要连接的 WiFi 网络并输入密码。</li></ol><p>完成上述步骤后，您的设备应能正常连接。</p><p>若仍无法连接，请通过 App 内的"问题反馈"功能提交您的问题，并附上订单截图，我们将尽快处理。</p>',
        ja: '<p><strong>A：</strong>以下の手順に従ってください：</p><ol><li>基地局の電源を入れ、BFOUR+ アプリを開き、基地局をスマートフォンの近くに置きます。</li><li>アプリを開き、ホーム画面で「デバイスを追加」をタップします。</li><li>リストから製品モデルを選択します。</li><li>検索ページで、モデル名に一致するデバイス（BF-70 または BF-80）をタップします。</li><li>「更新」をタップします。</li><li>接続したい Wi-Fi ネットワークを選択し、パスワードを入力します。</li></ol><p>上記の手順を完了すると、デバイスは正常に接続できるはずです。</p><p>それでも接続できない場合は、アプリ内の「問題フィードバック」機能から問題を送信し、注文のスクリーンショットを添付してください。できる限り早く対応いたします。</p>',
        de: '<p><strong>A:</strong> Bitte befolgen Sie die folgenden Schritte in der angegebenen Reihenfolge:</p><ol><li>Schalten Sie die Basisstation ein und öffnen Sie die BFOUR+-App, und platzieren Sie die Basisstation in der Nähe Ihres Telefons.</li><li>Öffnen Sie die App und tippen Sie auf dem Startbildschirm auf &quot;Gerät hinzufügen&quot;.</li><li>Wählen Sie Ihr Produktmodell aus der Liste.</li><li>Tippen Sie auf der Suchseite auf das Gerät, das zu Ihrem Modellnamen passt (BF-70 oder BF-80).</li><li>Tippen Sie auf &quot;Aktualisieren&quot;.</li><li>Wählen Sie das WLAN-Netzwerk, mit dem Sie sich verbinden möchten, und geben Sie das Passwort ein.</li></ol><p>Nachdem Sie die obigen Schritte abgeschlossen haben, sollte sich Ihr Gerät normal verbinden.</p><p>Wenn Sie immer noch keine Verbindung herstellen können, senden Sie Ihr Problem über die Funktion &quot;Problem-Feedback&quot; in der App ein und fügen Sie einen Screenshot Ihrer Bestellung bei. Wir werden es so schnell wie möglich bearbeiten.</p>',
        fr: '<p><strong>A :</strong> Veuillez suivre les étapes ci-dessous dans l\'ordre :</p><ol><li>Allumez la station de base et ouvrez l\'application BFOUR+, et placez la station de base près de votre téléphone.</li><li>Ouvrez l\'application et appuyez sur &quot;Ajouter un appareil&quot; sur l\'écran d\'accueil.</li><li>Sélectionnez votre modèle de produit dans la liste.</li><li>Sur la page de recherche, appuyez sur l\'appareil correspondant au nom de votre modèle (BF-70 ou BF-80).</li><li>Appuyez sur &quot;Actualiser&quot;.</li><li>Sélectionnez le réseau Wi-Fi auquel vous souhaitez vous connecter et saisissez le mot de passe.</li></ol><p>Une fois ces étapes terminées, votre appareil devrait pouvoir se connecter normalement.</p><p>Si vous ne parvenez toujours pas à vous connecter, veuillez soumettre votre problème via la fonction &quot;Signalement de problème&quot; dans l\'application, avec une capture d\'écran de votre commande, et nous le traiterons dès que possible.</p>',
        es: '<p><strong>A:</strong> Siga los siguientes pasos en orden:</p><ol><li>Encienda la estación base y abra la aplicación BFOUR+, y coloque la estación base cerca de su teléfono.</li><li>Abra la aplicación y toque &quot;Añadir dispositivo&quot; en la pantalla de inicio.</li><li>Seleccione su modelo de producto de la lista.</li><li>En la página de búsqueda, toque el dispositivo que coincida con el nombre de su modelo (BF-70 o BF-80).</li><li>Toque &quot;Actualizar&quot;.</li><li>Seleccione la red WiFi a la que desea conectarse e introduzca la contraseña.</li></ol><p>Una vez completados los pasos anteriores, su dispositivo debería poder conectarse normalmente.</p><p>Si aún no puede conectarse, envíe su problema a través de la función &quot;Comentarios de problemas&quot; en la aplicación, junto con una captura de pantalla de su pedido, y lo procesaremos lo antes posible.</p>'
      }
    },
    {
      q: {
        en: "My thermometer shows an &quot;Out of Range&quot; alert. What causes this and what should I do?",
        zh: "我的温度计显示&ldquo;超出范围&rdquo;警报，是什么原因，该怎么办？",
        ja: "温度計に「範囲外」アラートが表示されます。原因は何で、どうすればよいですか？",
        de: "Mein Thermometer zeigt eine &quot;Außerhalb des Bereichs&quot;-Warnung an. Was ist die Ursache und was soll ich tun?",
        fr: "Mon thermomètre affiche une alerte &quot;Hors de portée&quot;. Quelle en est la cause et que dois-je faire ?",
        es: "Mi termómetro muestra una alerta &quot;Fuera de rango&quot;. ¿Cuál es la causa y qué debo hacer?"
      },
      a: {
        en: '<p><strong>A:</strong>The &quot;Out of Range&quot; alert typically indicates that the signal connection between the probe and the receiver has been interrupted. Please follow the steps below to troubleshoot:</p><p><strong>1.Please make sure the probe is fully charged:<br /></strong>(1) BF-30 / BF-40: Charge on the base station for 2–3 minutes<br />(2) BF-70 / BF-80: Charge on the base station for 10–15 minutes</p><p>If the issue persists after charging, please try re-pairing / re-adding the probe with the receiver.</p><p><strong>2. Check the distance and signal interference</strong></p><p>(1) During use, please ensure the receiver is kept as close to the probe as possible.</p><p>(2) Check for signal obstructions such as:</p><p>Thick cookware (cast iron pots, double-layered stainless steel pots, etc.)</p><p>Other electronic devices (which may cause signal interference)</p><p>(3) You may also try placing the receiver near the front or side of the oven for better signal reception.</p><p><strong>3. Check the usage environment and temperature limits</strong></p><p>(1) Food temperature should be kept within the range of -10°C ~ 100°C</p><p>(2) Ambient temperature should be kept within the range of 0°C ~ 400°C</p><p>Please note: If the internal temperature of the meat exceeds the recommended safe value (for example, above the suggested doneness level), the system may also trigger an alert. Please check whether this applies to your situation.</p><p><strong>4. On-site test</strong></p><p>When the &quot;Out of Range&quot; alert appears, please try moving the receiver closer to the probe (e.g., next to the oven) and check whether the signal recovers.</p><p>If the issue persists after following the above steps, please submit your issue through the Problem Feedback feature in the app, along with a screenshot of your order, and we will process it as soon as possible.</p><p>Thank you for your cooperation!</p>',
        zh: '<p><strong>A：</strong>"超出范围"警报通常表示探针与接收器之间的信号连接被中断。请按以下步骤排查：</p><p><strong>1. 请确保探针已充满电：<br /></strong>(1) BF-30 / BF-40：在基站上充电 2–3 分钟<br />(2) BF-70 / BF-80：在基站上充电 10–15 分钟</p><p>若充电后问题依旧，请尝试将探针与接收器重新配对/重新添加。</p><p><strong>2. 检查距离与信号干扰</strong></p><p>(1) 使用时，请尽量让接收器靠近探针。</p><p>(2) 检查是否存在信号遮挡物：</p><p>厚重炊具（铸铁锅、双层不锈钢锅等）</p><p>其他电子设备（可能造成信号干扰）</p><p>(3) 您也可尝试将接收器放置在烤箱前方或侧面，以获得更好的信号接收效果。</p><p><strong>3. 检查使用环境与温度范围</strong></p><p>(1) 食物温度应保持在 -10°C ~ 100°C 范围内</p><p>(2) 环境温度应保持在 0°C ~ 400°C 范围内</p><p>请注意：若肉类内部温度超过建议安全值（例如超过建议的熟度），系统也可能触发警报。请检查是否属于此情况。</p><p><strong>4. 现场测试</strong></p><p>当出现"超出范围"警报时，请尝试将接收器移近探针（例如靠近烤箱），检查信号是否恢复。</p><p>若以上步骤后问题依旧，请通过 App 内的"问题反馈"功能提交您的问题，并附上订单截图，我们将尽快处理。</p><p>感谢您的配合！</p>',
        ja: '<p><strong>A：</strong>「範囲外」アラートは通常、プローブと受信機の間の信号接続が中断されたことを示します。以下の手順でトラブルシューティングしてください：</p><p><strong>1. プローブが完全に充電されていることを確認してください：<br /></strong>(1) BF-30 / BF-40：基地局で 2〜3 分間充電<br />(2) BF-70 / BF-80：基地局で 10〜15 分間充電</p><p>充電後も問題が続く場合は、プローブを受信機と再ペアリング/再追加してみてください。</p><p><strong>2. 距離と信号干渉を確認</strong></p><p>(1) 使用中は、受信機をできるだけプローブの近くに置いてください。</p><p>(2) 信号を遮るものがないか確認してください：</p><p>厚手の調理器具（鋳鉄鍋、二重層ステンレス鍋など）</p><p>他の電子機器（信号干渉の原因になる可能性があります）</p><p>(3) 受信機をオーブンの前面または側面に置くと、信号の受信が良くなる場合があります。</p><p><strong>3. 使用環境と温度範囲を確認</strong></p><p>(1) 食材温度は -10°C〜100°C の範囲に保ってください</p><p>(2) 環境温度は 0°C〜400°C の範囲に保ってください</p><p>注意：肉の内部温度が推奨安全値を超えた場合（例：推奨焼き加減を超えるなど）、システムがアラートを出すこともあります。該当するかご確認ください。</p><p><strong>4. 現地テスト</strong></p><p>「範囲外」アラートが出たら、受信機をプローブの近く（例：オーブンの横）に移動し、信号が回復するか確認してください。</p><p>上記の手順でも問題が続く場合は、アプリ内の「問題フィードバック」機能から問題を送信し、注文のスクリーンショットを添付してください。できる限り早く対応いたします。</p><p>ご協力ありがとうございます！</p>',
        de: '<p><strong>A:</strong> Die Warnung &quot;Außerhalb des Bereichs&quot; weist in der Regel darauf hin, dass die Signalverbindung zwischen Sonde und Empfänger unterbrochen wurde. Bitte befolgen Sie die folgenden Schritte zur Fehlerbehebung:</p><p><strong>1. Stellen Sie sicher, dass die Sonde vollständig geladen ist:<br /></strong>(1) BF-30 / BF-40: An der Basisstation 2–3 Minuten aufladen<br />(2) BF-70 / BF-80: An der Basisstation 10–15 Minuten aufladen</p><p>Wenn das Problem nach dem Aufladen weiterhin besteht, versuchen Sie, die Sonde mit dem Empfänger neu zu koppeln / neu hinzuzufügen.</p><p><strong>2. Entfernung und Signalstörungen prüfen</strong></p><p>(1) Halten Sie den Empfänger während der Verwendung so nah wie möglich an der Sonde.</p><p>(2) Prüfen Sie auf Signalhindernisse wie:</p><p>Dickes Kochgeschirr (Gusseisentöpfe, zweischichtige Edelstahltöpfe usw.)</p><p>Andere elektronische Geräte (die Signalstörungen verursachen können)</p><p>(3) Sie können auch versuchen, den Empfänger in der Nähe der Vorder- oder Seite des Ofens zu platzieren, um einen besseren Signalempfang zu erzielen.</p><p><strong>3. Nutzungsumgebung und Temperaturgrenzen prüfen</strong></p><p>(1) Die Lebensmitteltemperatur sollte im Bereich von -10°C bis 100°C gehalten werden</p><p>(2) Die Umgebungstemperatur sollte im Bereich von 0°C bis 400°C gehalten werden</p><p>Hinweis: Wenn die Innentemperatur des Fleisches den empfohlenen Sicherheitswert überschreitet (z. B. über dem empfohlenen Gargrad), kann das System ebenfalls eine Warnung auslösen. Bitte prüfen Sie, ob dies auf Ihre Situation zutrifft.</p><p><strong>4. Vor-Ort-Test</strong></p><p>Wenn die Warnung &quot;Außerhalb des Bereichs&quot; erscheint, versuchen Sie, den Empfänger näher an die Sonde zu bewegen (z. B. neben den Ofen) und prüfen Sie, ob das Signal wiederhergestellt wird.</p><p>Wenn das Problem nach den obigen Schritten weiterhin besteht, senden Sie Ihr Problem über die Funktion &quot;Problem-Feedback&quot; in der App ein und fügen Sie einen Screenshot Ihrer Bestellung bei. Wir werden es so schnell wie möglich bearbeiten.</p><p>Vielen Dank für Ihre Mithilfe!</p>',
        fr: '<p><strong>A :</strong> L\'alerte &quot;Hors de portée&quot; indique généralement que la connexion de signal entre la sonde et le récepteur a été interrompue. Veuillez suivre les étapes ci-dessous pour le dépannage :</p><p><strong>1. Assurez-vous que la sonde est entièrement chargée :<br /></strong>(1) BF-30 / BF-40 : Charger sur la station de base pendant 2 à 3 minutes<br />(2) BF-70 / BF-80 : Charger sur la station de base pendant 10 à 15 minutes</p><p>Si le problème persiste après la charge, essayez de ré-apparier / ré-ajouter la sonde avec le récepteur.</p><p><strong>2. Vérifiez la distance et les interférences de signal</strong></p><p>(1) Pendant l\'utilisation, veillez à garder le récepteur aussi près que possible de la sonde.</p><p>(2) Vérifiez les obstacles au signal tels que :</p><p>Ustensiles de cuisine épais (marmites en fonte, casseroles en acier inoxydable double couche, etc.)</p><p>Autres appareils électroniques (qui peuvent causer des interférences de signal)</p><p>(3) Vous pouvez également essayer de placer le récepteur près de l\'avant ou du côté du four pour une meilleure réception du signal.</p><p><strong>3. Vérifiez l\'environnement d\'utilisation et les limites de température</strong></p><p>(1) La température des aliments doit être maintenue dans la plage de -10°C à 100°C</p><p>(2) La température ambiante doit être maintenue dans la plage de 0°C à 400°C</p><p>Remarque : Si la température interne de la viande dépasse la valeur de sécurité recommandée (par exemple, au-dessus du niveau de cuisson suggéré), le système peut également déclencher une alerte. Veuillez vérifier si cela s\'applique à votre situation.</p><p><strong>4. Test sur place</strong></p><p>Lorsque l\'alerte &quot;Hors de portée&quot; apparaît, essayez de rapprocher le récepteur de la sonde (par exemple, à côté du four) et vérifiez si le signal est rétabli.</p><p>Si le problème persiste après les étapes ci-dessus, veuillez soumettre votre problème via la fonction &quot;Signalement de problème&quot; dans l\'application, avec une capture d\'écran de votre commande, et nous le traiterons dès que possible.</p><p>Merci de votre coopération !</p>',
        es: '<p><strong>A:</strong> La alerta &quot;Fuera de rango&quot; generalmente indica que la conexión de señal entre la sonda y el receptor se ha interrumpido. Siga los pasos a continuación para solucionar el problema:</p><p><strong>1. Asegúrese de que la sonda esté completamente cargada:<br /></strong>(1) BF-30 / BF-40: Cargar en la estación base durante 2–3 minutos<br />(2) BF-70 / BF-80: Cargar en la estación base durante 10–15 minutos</p><p>Si el problema persiste después de cargar, intente volver a emparejar / volver a añadir la sonda con el receptor.</p><p><strong>2. Compruebe la distancia y las interferencias de señal</strong></p><p>(1) Durante el uso, asegúrese de mantener el receptor lo más cerca posible de la sonda.</p><p>(2) Compruebe si hay obstrucciones de señal como:</p><p>Utensilios de cocina gruesos (ollas de hierro fundido, ollas de acero inoxidable de doble capa, etc.)</p><p>Otros dispositivos electrónicos (que pueden causar interferencias de señal)</p><p>(3) También puede intentar colocar el receptor cerca de la parte frontal o lateral del horno para una mejor recepción de señal.</p><p><strong>3. Compruebe el entorno de uso y los límites de temperatura</strong></p><p>(1) La temperatura de los alimentos debe mantenerse en el rango de -10°C a 100°C</p><p>(2) La temperatura ambiente debe mantenerse en el rango de 0°C a 400°C</p><p>Nota: Si la temperatura interna de la carne supera el valor seguro recomendado (por ejemplo, por encima del nivel de cocción sugerido), el sistema también puede activar una alerta. Compruebe si esto se aplica a su situación.</p><p><strong>4. Prueba in situ</strong></p><p>Cuando aparezca la alerta &quot;Fuera de rango&quot;, intente acercar el receptor a la sonda (por ejemplo, junto al horno) y compruebe si la señal se recupera.</p><p>Si el problema persiste después de los pasos anteriores, envíe su problema a través de la función &quot;Comentarios de problemas&quot; en la aplicación, junto con una captura de pantalla de su pedido, y lo procesaremos lo antes posible.</p><p>¡Gracias por su cooperación!</p>'
      }
    },
    {
      q: {
        en: "My thermometer frequently disconnects and the signal is unstable. What should I do?",
        zh: "我的温度计频繁断连、信号不稳定，该怎么办？",
        ja: "温度計が頻繁に切断され、信号が不安定です。どうすればよいですか？",
        de: "Mein Thermometer trennt die Verbindung häufig und das Signal ist instabil. Was soll ich tun?",
        fr: "Mon thermomètre se déconnecte fréquemment et le signal est instable. Que dois-je faire ?",
        es: "Mi termómetro se desconecta con frecuencia y la señal es inestable. ¿Qué debo hacer?"
      },
      a: {
        en: '<p><strong>A:</strong>Please follow the steps below to troubleshoot:</p><p><strong>1.Restart the device:</strong> Power off and restart the base station, and place the probe back into the base station then take it out again to allow the device to re-pair and reconnect.</p><p><strong>2.Reduce the distance: </strong>Place the base station close to the probe to ensure they are within the effective Bluetooth transmission range, and minimize obstacles in between (such as walls, metal objects, etc.).</p><p><strong>3.Avoid signal interference: </strong>Ensure the base station is kept away from other Bluetooth devices, Wi-Fi routers, or microwave ovens, as well as other electronic devices that may cause interference.</p><p><strong>4.Check battery level: </strong>Ensure both the probe and the base station have sufficient battery power, as low battery may also cause unstable connection.</p><p>If the issue persists after following the above steps, please submit your issue through the Problem Feedback feature in the app, along with a screenshot of your order, and we will process it as soon as possible.</p>',
        zh: '<p><strong>A：</strong>请按以下步骤排查：</p><p><strong>1. 重启设备：</strong>关闭并重启基站，将探针放回基站再取出，使设备重新配对连接。</p><p><strong>2. 缩短距离：</strong>将基站靠近探针放置，确保处于有效蓝牙传输范围内，并尽量减少中间障碍物（如墙壁、金属物体等）。</p><p><strong>3. 避免信号干扰：</strong>确保基站远离其他蓝牙设备、Wi-Fi 路由器或微波炉，以及其他可能造成干扰的电子设备。</p><p><strong>4. 检查电量：</strong>确保探针和基站电量充足，电量过低也可能导致连接不稳定。</p><p>若以上步骤后问题依旧，请通过 App 内的"问题反馈"功能提交您的问题，并附上订单截图，我们将尽快处理。</p>',
        ja: '<p><strong>A：</strong>以下の手順でトラブルシューティングしてください：</p><p><strong>1. デバイスを再起動：</strong>基地局の電源を切って再起動し、プローブを基地局に戻してから再び取り出し、デバイスを再ペアリング・再接続してください。</p><p><strong>2. 距離を縮める：</strong>基地局をプローブの近くに置き、有効な Bluetooth 伝送範囲内に収まるようにし、間の障害物（壁、金属物など）を最小限にしてください。</p><p><strong>3. 信号干渉を避ける：</strong>基地局を他の Bluetooth デバイス、Wi-Fi ルーター、電子レンジ、その他干渉の原因となる電子機器から遠ざけてください。</p><p><strong>4. バッテリーレベルを確認：</strong>プローブと基地局の両方に十分なバッテリーがあることを確認してください。バッテリー残量が低いと接続が不安定になることがあります。</p><p>上記の手順でも問題が続く場合は、アプリ内の「問題フィードバック」機能から問題を送信し、注文のスクリーンショットを添付してください。できる限り早く対応いたします。</p>',
        de: '<p><strong>A:</strong> Bitte befolgen Sie die folgenden Schritte zur Fehlerbehebung:</p><p><strong>1. Gerät neu starten:</strong> Schalten Sie die Basisstation aus und starten Sie sie neu, und legen Sie die Sonde wieder in die Basisstation und nehmen Sie sie dann wieder heraus, damit das Gerät sich neu koppelt und verbindet.</p><p><strong>2. Entfernung verringern:</strong> Platzieren Sie die Basisstation nah an der Sonde, um sicherzustellen, dass sie sich innerhalb der effektiven Bluetooth-Übertragungsreichweite befinden, und minimieren Sie Hindernisse dazwischen (wie Wände, Metallgegenstände usw.).</p><p><strong>3. Signalstörungen vermeiden:</strong> Stellen Sie sicher, dass die Basisstation von anderen Bluetooth-Geräten, WLAN-Routern oder Mikrowellen sowie anderen elektronischen Geräten ferngehalten wird, die Störungen verursachen könnten.</p><p><strong>4. Batteriestand prüfen:</strong> Stellen Sie sicher, dass sowohl die Sonde als auch die Basisstation über ausreichend Batterieleistung verfügen, da ein niedriger Batteriestand ebenfalls zu einer instabilen Verbindung führen kann.</p><p>Wenn das Problem nach den obigen Schritten weiterhin besteht, senden Sie Ihr Problem über die Funktion &quot;Problem-Feedback&quot; in der App ein und fügen Sie einen Screenshot Ihrer Bestellung bei. Wir werden es so schnell wie möglich bearbeiten.</p>',
        fr: '<p><strong>A :</strong> Veuillez suivre les étapes ci-dessous pour le dépannage :</p><p><strong>1. Redémarrez l\'appareil :</strong> Éteignez et redémarrez la station de base, et remettez la sonde dans la station de base puis retirez-la à nouveau pour permettre à l\'appareil de se ré-apparier et de se reconnecter.</p><p><strong>2. Réduisez la distance :</strong> Placez la station de base près de la sonde pour vous assurer qu\'ils sont dans la plage de transmission Bluetooth effective, et minimisez les obstacles entre eux (comme les murs, les objets métalliques, etc.).</p><p><strong>3. Évitez les interférences de signal :</strong> Assurez-vous que la station de base est tenue à l\'écart des autres appareils Bluetooth, des routeurs Wi-Fi ou des fours à micro-ondes, ainsi que d\'autres appareils électroniques susceptibles de causer des interférences.</p><p><strong>4. Vérifiez le niveau de batterie :</strong> Assurez-vous que la sonde et la station de base ont une batterie suffisante, car une batterie faible peut également causer une connexion instable.</p><p>Si le problème persiste après les étapes ci-dessus, veuillez soumettre votre problème via la fonction &quot;Signalement de problème&quot; dans l\'application, avec une capture d\'écran de votre commande, et nous le traiterons dès que possible.</p>',
        es: '<p><strong>A:</strong> Siga los pasos a continuación para solucionar el problema:</p><p><strong>1. Reinicie el dispositivo:</strong> Apague y reinicie la estación base, y coloque la sonda de nuevo en la estación base y luego sáquela nuevamente para permitir que el dispositivo se vuelva a emparejar y reconectar.</p><p><strong>2. Reduzca la distancia:</strong> Coloque la estación base cerca de la sonda para asegurar que estén dentro del rango efectivo de transmisión Bluetooth, y minimice los obstáculos intermedios (como paredes, objetos metálicos, etc.).</p><p><strong>3. Evite las interferencias de señal:</strong> Asegúrese de mantener la estación base alejada de otros dispositivos Bluetooth, routers Wi-Fi o microondas, así como de otros dispositivos electrónicos que puedan causar interferencias.</p><p><strong>4. Compruebe el nivel de batería:</strong> Asegúrese de que tanto la sonda como la estación base tengan suficiente batería, ya que una batería baja también puede causar una conexión inestable.</p><p>Si el problema persiste después de los pasos anteriores, envíe su problema a través de la función &quot;Comentarios de problemas&quot; en la aplicación, junto con una captura de pantalla de su pedido, y lo procesaremos lo antes posible.</p>'
      }
    },
    {
      q: {
        en: "After connecting, my device does not display the ambient temperature. What causes this and what should I do?",
        zh: "连接后，我的设备不显示环境温度，是什么原因，该怎么办？",
        ja: "接続後、デバイスに環境温度が表示されません。原因は何で、どうすればよいですか？",
        de: "Nach dem Verbinden zeigt mein Gerät die Umgebungstemperatur nicht an. Was ist die Ursache und was soll ich tun?",
        fr: "Après la connexion, mon appareil n\'affiche pas la température ambiante. Quelle en est la cause et que dois-je faire ?",
        es: "Después de conectar, mi dispositivo no muestra la temperatura ambiente. ¿Cuál es la causa y qué debo hacer?"
      },
      a: {
        en: '<p><strong>A: </strong>Please follow the steps below to confirm:</p><p><strong>1. Check the probe insertion method</strong></p><p>Please insert the probe into the thickest part of the meat, and make sure all safety lines on the probe are fully submerged into the meat.</p><p><strong>2. Confirm the display interface</strong></p><p>After proper placement, the base station and the app interface should display both &quot;Internal Temperature&quot; and &quot;Ambient Temperature&quot; simultaneously. Please check carefully.</p><p><strong>3. Check the Bluetooth connection status</strong></p><p>(1) Please confirm whether the connection between the base station and the probe is stable.</p><p>(2) Try moving the base station closer to the probe.</p><p>(3) Or place the probe back into the base station, then take it out again to re-pair.</p><p><strong>4. Ambient temperature sensor notes (please pay attention)</strong></p><p>(1) The measuring range of the ambient temperature is 20–400°C. It will not display below 20°C.</p><p>(2) The ambient temperature sensor is embedded near the top of the probe\'s ceramic handle.</p><p><strong>5. Common causes of abnormal temperature display</strong></p><p>(1) It takes longer for heat to transfer through the ceramic handle to the sensor.</p><p>(2) Cold meat can conduct low temperature through the stainless steel probe to the sensor, affecting the initial reading.</p><p>This is a normal phenomenon. During low-temperature cooking, the ambient temperature reading will gradually become accurate as cooking time extends.</p><p>If the issue persists after following the above steps, please submit your issue through the Problem Feedback feature in the app, along with a screenshot of your order, and we will process it as soon as possible.</p><p>Thank you for your cooperation and understanding!</p>',
        zh: '<p><strong>A：</strong>请按以下步骤确认：</p><p><strong>1. 检查探针插入方式</strong></p><p>请将探针插入肉类最厚处，并确保探针上的安全线全部没入肉中。</p><p><strong>2. 确认显示界面</strong></p><p>正确放置后，基站和 App 界面应同时显示"内部温度"和"环境温度"。请仔细查看。</p><p><strong>3. 检查蓝牙连接状态</strong></p><p>(1) 请确认基站与探针之间的连接是否稳定。</p><p>(2) 尝试将基站移近探针。</p><p>(3) 或将探针放回基站再取出，重新配对。</p><p><strong>4. 环境温度传感器注意事项（请留意）</strong></p><p>(1) 环境温度测量范围为 20–400°C，低于 20°C 不显示。</p><p>(2) 环境温度传感器内嵌于探针陶瓷手柄顶部附近。</p><p><strong>5. 温度显示异常的常见原因</strong></p><p>(1) 热量通过陶瓷手柄传导到传感器需要较长时间。</p><p>(2) 冷肉会通过不锈钢探针将低温传导至传感器，影响初始读数。</p><p>此为正常现象。低温烹饪时，随着烹饪时间延长，环境温度读数会逐渐准确。</p><p>若以上步骤后问题依旧，请通过 App 内的"问题反馈"功能提交您的问题，并附上订单截图，我们将尽快处理。</p><p>感谢您的配合与理解！</p>',
        ja: '<p><strong>A：</strong>以下の手順で確認してください：</p><p><strong>1. プローブの挿入方法を確認</strong></p><p>プローブを肉の最も厚い部分に挿入し、プローブの安全ラインがすべて肉の中に完全に沈んでいることを確認してください。</p><p><strong>2. 表示インターフェースを確認</strong></p><p>正しく配置した後、基地局とアプリ画面に「内部温度」と「環境温度」の両方が同時に表示されるはずです。よく確認してください。</p><p><strong>3. Bluetooth 接続状態を確認</strong></p><p>(1) 基地局とプローブの接続が安定しているか確認してください。</p><p>(2) 基地局をプローブの近くに移動してみてください。</p><p>(3) またはプローブを基地局に戻し、再び取り出して再ペアリングしてください。</p><p><strong>4. 環境温度センサーの注意事項（ご注意ください）</strong></p><p>(1) 環境温度の測定範囲は 20〜400°C です。20°C 未満では表示されません。</p><p>(2) 環境温度センサーはプローブのセラミックハンドル上部付近に埋め込まれています。</p><p><strong>5. 温度表示異常の一般的な原因</strong></p><p>(1) 熱がセラミックハンドルを通じてセンサーに伝わるには時間がかかります。</p><p>(2) 冷たい肉はステンレスプローブを通じて低温をセンサーに伝え、初期の読み取り値に影響を与えることがあります。</p><p>これは正常な現象です。低温調理では、調理時間が長くなるにつれて環境温度の読み取り値が徐々に正確になります。</p><p>上記の手順でも問題が続く場合は、アプリ内の「問題フィードバック」機能から問題を送信し、注文のスクリーンショットを添付してください。できる限り早く対応いたします。</p><p>ご協力とご理解ありがとうございます！</p>',
        de: '<p><strong>A:</strong> Bitte bestätigen Sie mit den folgenden Schritten:</p><p><strong>1. Überprüfen Sie die Einfühlmethode der Sonde</strong></p><p>Bitte führen Sie die Sonde in den dicksten Teil des Fleisches ein und stellen Sie sicher, dass alle Sicherheitslinien auf der Sonde vollständig in das Fleisch eingetaucht sind.</p><p><strong>2. Bestätigen Sie die Anzeigeschnittstelle</strong></p><p>Nach ordnungsgemäßer Platzierung sollten die Basisstation und die App-Oberfläche gleichzeitig &quot;Innentemperatur&quot; und &quot;Umgebungstemperatur&quot; anzeigen. Bitte prüfen Sie sorgfältig.</p><p><strong>3. Bluetooth-Verbindungsstatus prüfen</strong></p><p>(1) Bitte bestätigen Sie, ob die Verbindung zwischen Basisstation und Sonde stabil ist.</p><p>(2) Versuchen Sie, die Basisstation näher an die Sonde zu bewegen.</p><p>(3) Oder legen Sie die Sonde zurück in die Basisstation und nehmen Sie sie dann wieder heraus, um neu zu koppeln.</p><p><strong>4. Hinweise zum Umgebungstemperatursensor (bitte beachten)</strong></p><p>(1) Der Messbereich der Umgebungstemperatur beträgt 20–400°C. Unter 20°C wird sie nicht angezeigt.</p><p>(2) Der Umgebungstemperatursensor ist in der Nähe des oberen Endes des keramischen Griffs der Sonde eingelassen.</p><p><strong>5. Häufige Ursachen für abnormale Temperaturanzeige</strong></p><p>(1) Es dauert länger, bis Wärme über den keramischen Griff zum Sensor übertragen wird.</p><p>(2) Kaltes Fleisch kann niedrige Temperatur über die Edelstahlsonde an den Sensor weiterleiten und die anfängliche Messung beeinträchtigen.</p><p>Dies ist ein normales Phänomen. Beim Niedertemperaturgaren wird die Umgebungstemperaturanzeige mit zunehmender Garzeit allmählich genauer.</p><p>Wenn das Problem nach den obigen Schritten weiterhin besteht, senden Sie Ihr Problem über die Funktion &quot;Problem-Feedback&quot; in der App ein und fügen Sie einen Screenshot Ihrer Bestellung bei. Wir werden es so schnell wie möglich bearbeiten.</p><p>Vielen Dank für Ihre Mithilfe und Ihr Verständnis!</p>',
        fr: '<p><strong>A :</strong> Veuillez confirmer avec les étapes suivantes :</p><p><strong>1. Vérifiez la méthode d\'insertion de la sonde</strong></p><p>Veuillez insérer la sonde dans la partie la plus épaisse de la viande et vous assurer que toutes les lignes de sécurité sur la sonde sont entièrement immergées dans la viande.</p><p><strong>2. Confirmez l\'interface d\'affichage</strong></p><p>Après un placement correct, la station de base et l\'interface de l\'application devraient afficher simultanément la « Température interne » et la « Température ambiante ». Veuillez vérifier attentivement.</p><p><strong>3. Vérifiez l\'état de la connexion Bluetooth</strong></p><p>(1) Veuillez confirmer si la connexion entre la station de base et la sonde est stable.</p><p>(2) Essayez de rapprocher la station de base de la sonde.</p><p>(3) Ou remettez la sonde dans la station de base, puis retirez-la à nouveau pour la ré-apparier.</p><p><strong>4. Remarques sur le capteur de température ambiante (veuillez prêter attention)</strong></p><p>(1) La plage de mesure de la température ambiante est de 20–400°C. Elle ne s\'affiche pas en dessous de 20°C.</p><p>(2) Le capteur de température ambiante est intégré près du sommet de la poignée en céramique de la sonde.</p><p><strong>5. Causes courantes d\'affichage anormal de la température</strong></p><p>(1) Il faut plus de temps pour que la chaleur soit transférée au capteur via la poignée en céramique.</p><p>(2) La viande froide peut conduire une basse température à travers la sonde en acier inoxydable vers le capteur, affectant la lecture initiale.</p><p>C\'est un phénomène normal. Lors de la cuisson à basse température, la lecture de la température ambiante deviendra progressivement précise au fur et à mesure que le temps de cuisson s\'allonge.</p><p>Si le problème persiste après les étapes ci-dessus, veuillez soumettre votre problème via la fonction &quot;Signalement de problème&quot; dans l\'application, avec une capture d\'écran de votre commande, et nous le traiterons dès que possible.</p><p>Merci de votre coopération et de votre compréhension !</p>',
        es: '<p><strong>A:</strong> Confirme con los siguientes pasos:</p><p><strong>1. Compruebe el método de inserción de la sonda</strong></p><p>Inserte la sonda en la parte más gruesa de la carne y asegúrese de que todas las líneas de seguridad de la sonda estén completamente sumergidas en la carne.</p><p><strong>2. Confirme la interfaz de visualización</strong></p><p>Después de colocar correctamente, la estación base y la interfaz de la aplicación deberían mostrar simultáneamente la «Temperatura interna» y la «Temperatura ambiente». Compruébelo cuidadosamente.</p><p><strong>3. Compruebe el estado de la conexión Bluetooth</strong></p><p>(1) Confirme si la conexión entre la estación base y la sonda es estable.</p><p>(2) Intente acercar la estación base a la sonda.</p><p>(3) O vuelva a colocar la sonda en la estación base y luego sáquela nuevamente para volver a emparejarla.</p><p><strong>4. Notas sobre el sensor de temperatura ambiente (preste atención)</strong></p><p>(1) El rango de medición de la temperatura ambiente es de 20–400°C. No se muestra por debajo de 20°C.</p><p>(2) El sensor de temperatura ambiente está integrado cerca de la parte superior del mango de cerámica de la sonda.</p><p><strong>5. Causas comunes de visualización anormal de la temperatura</strong></p><p>(1) Tarda más en que el calor se transfiera al sensor a través del mango de cerámica.</p><p>(2) La carne fría puede conducir una temperatura baja a través de la sonda de acero inoxidable al sensor, afectando la lectura inicial.</p><p>Este es un fenómeno normal. Durante la cocción a baja temperatura, la lectura de la temperatura ambiente se volverá gradualmente precisa a medida que se prolongue el tiempo de cocción.</p><p>Si el problema persiste después de los pasos anteriores, envíe su problema a través de la función &quot;Comentarios de problemas&quot; en la aplicación, junto con una captura de pantalla de su pedido, y lo procesaremos lo antes posible.</p><p>¡Gracias por su cooperación y comprensión!</p>'
      }
    },
    {
      q: {
        en: "My thermometer readings are inaccurate and differ from those of my instant-read thermometer. What should I do?",
        zh: "我的温度计读数不准，与即时读数温度计有差异，该怎么办？",
        ja: "温度計の読み取り値が不正確で、即読み温度計と異なります。どうすればよいですか？",
        de: "Die Messwerte meines Thermometers sind ungenau und weichen von denen meines Sofortlese-Thermometers ab. Was soll ich tun?",
        fr: "Les relevés de mon thermomètre sont inexacts et diffèrent de ceux de mon thermomètre à lecture instantanée. Que dois-je faire ?",
        es: "Las lecturas de mi termómetro son inexactas y difieren de las de mi termómetro de lectura instantánea. ¿Qué debo hacer?"
      },
      a: {
        en: '<p><strong>A: </strong>Our wireless probe is specifically designed for low-power long-term monitoring. Temperature readings are taken every 2 seconds and updated via Bluetooth. Its heating response speed cannot be directly compared to that of a plug-and-play instant-read thermometer, and the time required to reach thermal equilibrium is much slower. However, if you continuously monitor the temperature during cooking, its readings are accurate and reliable.</p><p>We recommend using the ice water calibration method for testing and verification:</p><p><strong>1.</strong>Fill a glass with ice cubes.</p><p><strong>2.</strong>Add cold water and stir for about 15 seconds.</p><p><strong>3.</strong>Fully submerge the probe in the center of the ice water.</p><p><strong>4.</strong>Let it sit for 15 seconds, then read the value.</p><p>Under normal conditions, the reading in the ice water mixture should be close to 0°C. If the deviation is significant, please submit your issue through the Problem Feedback feature in the app, along with a screenshot of your order, and we will process it as soon as possible.</p>',
        zh: '<p><strong>A：</strong>我们的无线探针专为低功耗长期监测而设计。温度每 2 秒读取一次并通过蓝牙更新。其加热响应速度无法与即插即用的即时读数温度计直接相比，达到热平衡所需的时间也慢得多。但在烹饪过程中持续监测温度时，其读数是准确可靠的。</p><p>建议使用冰水校准法进行测试验证：</p><p><strong>1.</strong>在玻璃杯中放入冰块。</p><p><strong>2.</strong>加入冷水搅拌约 15 秒。</p><p><strong>3.</strong>将探针完全浸入冰水中央。</p><p><strong>4.</strong>静置 15 秒后读取数值。</p><p>正常情况下，冰水混合物中的读数应接近 0°C。若偏差较大，请通过 App 内的"问题反馈"功能提交您的问题，并附上订单截图，我们将尽快处理。</p>',
        ja: '<p><strong>A：</strong>当社のワイヤレスプローブは低消費電力の長期モニタリング用に特別に設計されています。温度読み取りは2秒ごとに行われ、Bluetooth 経由で更新されます。その加熱応答速度はプラグアンドプレイの即読み温度計と直接比較できず、熱平衡に達するのに必要な時間もはるかに遅いです。ただし、調理中に温度を継続的に監視すれば、その読み取り値は正確で信頼できます。</p><p>テストと検証には氷水校正法の使用をお勧めします：</p><p><strong>1.</strong>グラスに氷を入れます。</p><p><strong>2.</strong>冷水を加え、約15秒間かき混ぜます。</p><p><strong>3.</strong>プローブを氷水の中央に完全に沈めます。</p><p><strong>4.</strong>15秒間置き、値を読み取ります。</p><p>通常の条件下では、氷水混合物の読み取り値は0°Cに近いはずです。偏差が大きい場合は、アプリ内の「問題フィードバック」機能から問題を送信し、注文のスクリーンショットを添付してください。できる限り早く対応いたします。</p>',
        de: '<p><strong>A:</strong> Unsere kabellose Sonde ist speziell für die langfristige Überwachung mit geringem Stromverbrauch konzipiert. Temperaturmessungen werden alle 2 Sekunden erfasst und per Bluetooth aktualisiert. Ihre Erwärmungsansprechgeschwindigkeit lässt sich nicht direkt mit der eines steck-und-spiel-Sofortlese-Thermometers vergleichen, und die Zeit bis zum Erreichen des thermischen Gleichgewichts ist deutlich langsamer. Wenn Sie jedoch die Temperatur während des Kochens kontinuierlich überwachen, sind die Messwerte genau und zuverlässig.</p><p>Wir empfehlen die Kalibrierungsmethode mit Eiswasser für Test und Verifizierung:</p><p><strong>1.</strong>Füllen Sie ein Glas mit Eiswürfeln.</p><p><strong>2.</strong>Geben Sie kaltes Wasser hinzu und rühren Sie etwa 15 Sekunden lang.</p><p><strong>3.</strong>Tauchen Sie die Sonde vollständig in die Mitte des Eiswassers ein.</p><p><strong>4.</strong>Lassen Sie sie 15 Sekunden stehen und lesen Sie dann den Wert ab.</p><p>Unter normalen Bedingungen sollte die Anzeige im Eiswasser-Gemisch nahe 0°C liegen. Wenn die Abweichung erheblich ist, senden Sie Ihr Problem über die Funktion &quot;Problem-Feedback&quot; in der App ein und fügen Sie einen Screenshot Ihrer Bestellung bei. Wir werden es so schnell wie möglich bearbeiten.</p>',
        fr: '<p><strong>A :</strong> Notre sonde sans fil est spécialement conçue pour une surveillance à long terme à faible consommation. Les relevés de température sont pris toutes les 2 secondes et mis à jour via Bluetooth. Sa vitesse de réponse à la chauffe ne peut pas être directement comparée à celle d\'un thermomètre à lecture instantanée plug-and-play, et le temps nécessaire pour atteindre l\'équilibre thermique est beaucoup plus lent. Cependant, si vous surveillez continuellement la température pendant la cuisson, ses relevés sont exacts et fiables.</p><p>Nous recommandons d\'utiliser la méthode d\'étalonnage à l\'eau glacée pour tester et vérifier :</p><p><strong>1.</strong>Remplissez un verre de glaçons.</p><p><strong>2.</strong>Ajoutez de l\'eau froide et remuez pendant environ 15 secondes.</p><p><strong>3.</strong>Plongez entièrement la sonde au centre de l\'eau glacée.</p><p><strong>4.</strong>Laissez reposer 15 secondes, puis lisez la valeur.</p><p>En conditions normales, la lecture dans le mélange d\'eau glacée devrait être proche de 0°C. Si l\'écart est important, veuillez soumettre votre problème via la fonction &quot;Signalement de problème&quot; dans l\'application, avec une capture d\'écran de votre commande, et nous le traiterons dès que possible.</p>',
        es: '<p><strong>A:</strong> Nuestra sonda inalámbrica está diseñada específicamente para la monitorización a largo plazo de bajo consumo. Las lecturas de temperatura se toman cada 2 segundos y se actualizan vía Bluetooth. Su velocidad de respuesta de calentamiento no se puede comparar directamente con la de un termómetro de lectura instantánea de conexión directa, y el tiempo necesario para alcanzar el equilibrio térmico es mucho más lento. Sin embargo, si supervisa continuamente la temperatura durante la cocción, sus lecturas son precisas y fiables.</p><p>Recomendamos utilizar el método de calibración con agua helada para probar y verificar:</p><p><strong>1.</strong>Llene un vaso con cubitos de hielo.</p><p><strong>2.</strong>Añada agua fría y remueva durante unos 15 segundos.</p><p><strong>3.</strong>Sumerja completamente la sonda en el centro del agua helada.</p><p><strong>4.</strong>Deje reposar 15 segundos y luego lea el valor.</p><p>En condiciones normales, la lectura en la mezcla de agua helada debería ser cercana a 0°C. Si la desviación es significativa, envíe su problema a través de la función &quot;Comentarios de problemas&quot; en la aplicación, junto con una captura de pantalla de su pedido, y lo procesaremos lo antes posible.</p>'
      }
    },
    {
      q: {
        en: "I feel that the battery life of my thermometer is not long enough. What should I do?",
        zh: "我觉得温度计的续航不够长，该怎么办？",
        ja: "温度計のバッテリー寿命が十分でないと感じます。どうすればよいですか？",
        de: "Ich finde, die Akkulaufzeit meines Thermometers ist nicht lang genug. Was soll ich tun?",
        fr: "Je trouve que l\'autonomie de la batterie de mon thermomètre n\'est pas assez longue. Que dois-je faire ?",
        es: "Siento que la duración de la batería de mi termómetro no es lo suficientemente larga. ¿Qué debo hacer?"
      },
      a: {
        en: '<p><strong>A: </strong>Please first confirm the following:</p><p><strong>1. Ensure both devices are fully charged</strong></p><p>BF-30 / BF-40: Place the probe on the base station and charge for 3–5 minutes.</p><p>BF-70 / BF-80: Place the probe on the base station and charge for 10–15 minutes.</p><p><strong>2. Notes on the battery indicator</strong></p><p>The battery percentage displayed on the base station is not absolutely accurate. Occasionally, it may show only one bar of battery remaining, but the device can still function normally for a considerable period. Please rest assured on this point.</p><p><strong>3. Normal battery life (when fully charged)</strong></p><p>BF-30 / BF-40: Probe battery life 40 hours, base station battery life 90 hours</p><p>BF-70 / BF-80: Probe battery life 33 hours, base station battery life 24 hours</p><p><strong>4. Battery specifications</strong></p><p>Our products are equipped with the following batteries:</p><p>BF-30 / BF-40: 500mAh, 3.7V</p><p>BF-70 / BF-80: 2600mAh, 3.7V</p><p>If the battery life is still insufficient, please submit your issue through the Problem Feedback feature in the app, along with a screenshot of your order, and we will process it as soon as possible.</p>',
        zh: '<p><strong>A：</strong>请先确认以下事项：</p><p><strong>1. 确保两台设备均已充满电</strong></p><p>BF-30 / BF-40：将探针放在基站上充电 3–5 分钟。</p><p>BF-70 / BF-80：将探针放在基站上充电 10–15 分钟。</p><p><strong>2. 电量指示说明</strong></p><p>基站上显示的电量百分比并非绝对准确。有时可能只显示一格电量，但设备仍可正常工作相当长时间。请放心使用。</p><p><strong>3. 正常续航（满电状态下）</strong></p><p>BF-30 / BF-40：探针续航 40 小时，基站续航 90 小时</p><p>BF-70 / BF-80：探针续航 33 小时，基站续航 24 小时</p><p><strong>4. 电池规格</strong></p><p>我们的产品配备以下电池：</p><p>BF-30 / BF-40：500mAh，3.7V</p><p>BF-70 / BF-80：2600mAh，3.7V</p><p>若续航仍不足，请通过 App 内的"问题反馈"功能提交您的问题，并附上订单截图，我们将尽快处理。</p>',
        ja: '<p><strong>A：</strong>まず以下の点を確認してください：</p><p><strong>1. 両デバイスが完全に充電されていることを確認</strong></p><p>BF-30 / BF-40：プローブを基地局に置き、3〜5分間充電します。</p><p>BF-70 / BF-80：プローブを基地局に置き、10〜15分間充電します。</p><p><strong>2. バッテリーインジケーターに関する注意</strong></p><p>基地局に表示されるバッテリー残量パーセンテージは絶対的に正確ではありません。時々バッテリー残量1本だけを表示することがありますが、デバイスはかなりの期間正常に機能できます。この点はご安心ください。</p><p><strong>3. 通常のバッテリー寿命（満充電時）</strong></p><p>BF-30 / BF-40：プローブバッテリー寿命40時間、基地局バッテリー寿命90時間</p><p>BF-70 / BF-80：プローブバッテリー寿命33時間、基地局バッテリー寿命24時間</p><p><strong>4. バッテリー仕様</strong></p><p>当社製品には以下のバッテリーが搭載されています：</p><p>BF-30 / BF-40：500mAh、3.7V</p><p>BF-70 / BF-80：2600mAh、3.7V</p><p>バッテリー寿命がまだ不十分な場合は、アプリ内の「問題フィードバック」機能から問題を送信し、注文のスクリーンショットを添付してください。できる限り早く対応いたします。</p>',
        de: '<p><strong>A:</strong> Bitte bestätigen Sie zunächst Folgendes:</p><p><strong>1. Stellen Sie sicher, dass beide Geräte vollständig geladen sind</strong></p><p>BF-30 / BF-40: Legen Sie die Sonde auf die Basisstation und laden Sie sie 3–5 Minuten lang.</p><p>BF-70 / BF-80: Legen Sie die Sonde auf die Basisstation und laden Sie sie 10–15 Minuten lang.</p><p><strong>2. Hinweise zur Batterieanzeige</strong></p><p>Der auf der Basisstation angezeigte Batterieprozentsatz ist nicht absolut genau. Gelegentlich wird nur noch ein Balken Batterie angezeigt, aber das Gerät kann noch über einen beträchtlichen Zeitraum normal funktionieren. Bitte seien Sie diesbezüglich beruhigt.</p><p><strong>3. Normale Akkulaufzeit (bei voller Ladung)</strong></p><p>BF-30 / BF-40: Akkulaufzeit der Sonde 40 Stunden, Akkulaufzeit der Basisstation 90 Stunden</p><p>BF-70 / BF-80: Akkulaufzeit der Sonde 33 Stunden, Akkulaufzeit der Basisstation 24 Stunden</p><p><strong>4. Batteriespezifikationen</strong></p><p>Unsere Produkte sind mit folgenden Batterien ausgestattet:</p><p>BF-30 / BF-40: 500mAh, 3.7V</p><p>BF-70 / BF-80: 2600mAh, 3.7V</p><p>Wenn die Akkulaufzeit immer noch unzureichend ist, senden Sie Ihr Problem über die Funktion &quot;Problem-Feedback&quot; in der App ein und fügen Sie einen Screenshot Ihrer Bestellung bei. Wir werden es so schnell wie möglich bearbeiten.</p>',
        fr: '<p><strong>A :</strong> Veuillez d\'abord confirmer les points suivants :</p><p><strong>1. Assurez-vous que les deux appareils sont entièrement chargés</strong></p><p>BF-30 / BF-40 : Placez la sonde sur la station de base et chargez pendant 3 à 5 minutes.</p><p>BF-70 / BF-80 : Placez la sonde sur la station de base et chargez pendant 10 à 15 minutes.</p><p><strong>2. Remarques sur l\'indicateur de batterie</strong></p><p>Le pourcentage de batterie affiché sur la station de base n\'est pas absolument précis. Parfois, il peut n\'afficher qu\'une barre de batterie restante, mais l\'appareil peut encore fonctionner normalement pendant une période considérable. Soyez rassuré sur ce point.</p><p><strong>3. Autonomie normale de la batterie (lorsqu\'elle est entièrement chargée)</strong></p><p>BF-30 / BF-40 : Autonomie de la sonde 40 heures, autonomie de la station de base 90 heures</p><p>BF-70 / BF-80 : Autonomie de la sonde 33 heures, autonomie de la station de base 24 heures</p><p><strong>4. Spécifications de la batterie</strong></p><p>Nos produits sont équipés des batteries suivantes :</p><p>BF-30 / BF-40 : 500mAh, 3.7V</p><p>BF-70 / BF-80 : 2600mAh, 3.7V</p><p>Si l\'autonomie de la batterie est toujours insuffisante, veuillez soumettre votre problème via la fonction &quot;Signalement de problème&quot; dans l\'application, avec une capture d\'écran de votre commande, et nous le traiterons dès que possible.</p>',
        es: '<p><strong>A:</strong> Primero confirme lo siguiente:</p><p><strong>1. Asegúrese de que ambos dispositivos estén completamente cargados</strong></p><p>BF-30 / BF-40: Coloque la sonda en la estación base y cargue durante 3–5 minutos.</p><p>BF-70 / BF-80: Coloque la sonda en la estación base y cargue durante 10–15 minutos.</p><p><strong>2. Notas sobre el indicador de batería</strong></p><p>El porcentaje de batería que se muestra en la estación base no es absolutamente preciso. Ocasionalmente, puede mostrar solo una barra de batería restante, pero el dispositivo aún puede funcionar con normalidad durante un período considerable. Esté tranquilo respecto a este punto.</p><p><strong>3. Duración normal de la batería (cuando está completamente cargada)</strong></p><p>BF-30 / BF-40: Duración de la batería de la sonda 40 horas, duración de la batería de la estación base 90 horas</p><p>BF-70 / BF-80: Duración de la batería de la sonda 33 horas, duración de la batería de la estación base 24 horas</p><p><strong>4. Especificaciones de la batería</strong></p><p>Nuestros productos están equipados con las siguientes baterías:</p><p>BF-30 / BF-40: 500mAh, 3.7V</p><p>BF-70 / BF-80: 2600mAh, 3.7V</p><p>Si la duración de la batería sigue siendo insuficiente, envíe su problema a través de la función &quot;Comentarios de problemas&quot; en la aplicación, junto con una captura de pantalla de su pedido, y lo procesaremos lo antes posible.</p>'
      }
    }
  ]
};
